import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './global.css'

const plusJakartaSans = localFont({
	src: [
		{
			path: '../public/fonts/PlusJakartaSans-Regular.woff2',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../public/fonts/PlusJakartaSans-Medium.woff2',
			weight: '500',
			style: 'normal',
		},
		{
			path: '../public/fonts/PlusJakartaSans-Bold.woff2',
			weight: '700',
			style: 'normal',
		},
	],
	display: 'swap',
	variable: '--font-plus-jakarta',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${plusJakartaSans.className}`}>{children}</body>
		</html>
	)
}
